apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aczp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aczp
    app.kubernetes.io/part-of: ci1t-43256-0088-app
  name: devfile-sample-aczp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aczp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aczp
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0088-tenant/ci1t-43256-0088-app/devfile-sample-aczp@sha256:2db17b72f370ef1233019a0a68b8bbdd75d43b978d9fb7e37bb35a1f38533375
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
